### ISSUE TITLE
Naming things

### ISSUE THREAD

**Issue by joakim** [tc39/proposal-record-tuple#207] opened 2020-11-25 02:24 UTC
Do the names `Tuple` and `Record` fit? As far as I can tell, they are essentially immutable `Array` and immutable `Object`, sharing both syntax and methods with their mutable counterparts.

When I think of tuples and records I think of lightweight data structures with a small footprint (memory and associated methods), not necessarily immutable. [Swift's tuples](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID329) for example.

I do like this proposal and what it brings to the language. But are they really tuples and records? Are they not immutable arrays and immutable objects?

**Comment by rricard** [comment] 2020-11-25 10:49
This issue is a duplicate of #82

**Closed by rricard** 2020-11-25 10:49 UTC

**Comment by joakim** [comment] 2020-11-25 11:10
My bad! I did search first but didn't find that issue.
